import { NextResponse } from 'next/server';

export async function GET() {
  return NextResponse.json({
    entries: [
      { id: 'l01', timestamp: '14:32:01', type: 'scan', target: 'prod-cluster', message: 'Completed infrastructure health scan. 2 critical issues found: prod-worker-03 memory at 96%, disk usage at 72%.', reasoning: 'Scanned 6 servers and 8 containers. Evaluated CPU, RAM, disk metrics against configured thresholds. prod-worker-03 exceeds critical threshold for RAM (96% > 90%).' },
      { id: 'l02', timestamp: '14:28:45', type: 'fix', target: 'axiom-api', message: 'Generated fix PR #142 for OOM error — increased Node.js memory limit from 2GB to 4GB in Dockerfile.', reasoning: 'Analyzed pipeline log for axiom-api. Error signature matches Node.js heap exhaustion during tsc compilation. The project has grown significantly; 2GB is no longer sufficient. Recommended fix: increase --max-old-space-size to 4096.' },
      { id: 'l03', timestamp: '14:22:10', type: 'diagnose', target: 'infra-deploy', message: 'Root cause: Terraform state lock held by terminated CI job run-4821. Lock ID: a1b2c3d4-e5f6-7890.', reasoning: 'Checked Terraform state lock metadata. Lock was acquired by CI job run-4821 at 11:22 UTC but the job was terminated at 11:45 UTC without releasing the lock. Safe to force-unlock as no concurrent apply is running.' },
      { id: 'l04', timestamp: '14:15:33', type: 'flag', target: 'gpu-training-01', message: 'Flagged idle GPU instance. No compute activity for 72 hours. Estimated waste: ₹4,800/mo.', reasoning: 'GPU utilization has been 0% for 72 consecutive hours. Network I/O is negligible (0.1 MB/s in, 0.02 MB/s out). Instance type p3.2xlarge costs ₹160/day. No scheduled training jobs found in the queue.' },
      { id: 'l05', timestamp: '14:10:02', type: 'scan', target: 'finops', message: 'Monthly cost scan complete. Total spend: ₹1,82,400. Waste identified: ₹14,200.', reasoning: 'Analyzed cost data across all linked AWS accounts. Identified 4 resources with significant waste: gpu-training-01 (₹4,800), staging-db-replica (₹3,200), vol-ml-checkpoints (₹3,600), ml-worker-stale (₹2,400).' },
      { id: 'l06', timestamp: '14:05:18', type: 'recommend', target: 'staging-db', message: 'Recommend downgrading staging-db from db.r5.xlarge to db.r5.large — 40% cost reduction.', reasoning: 'Staging database CPU average is 22% and peak is 38% over the last 30 days. Memory utilization averages 34%. db.r5.large provides sufficient headroom. Estimated monthly saving: ₹2,100.' },
      { id: 'l07', timestamp: '13:55:42', type: 'fix', target: 'ml-pipeline', message: 'Generated fix PR #89 — reduced batch_size from 64 to 32 with gradient accumulation steps=2.', reasoning: 'CUDA OOM error during model loading. GPU has 16 GiB total, 12.8 GiB already allocated. Reducing batch size to 32 halves memory requirement while gradient accumulation maintains effective batch size.' },
      { id: 'l08', timestamp: '13:48:15', type: 'scan', target: 'containers', message: 'Container health scan complete. Found 2 idle containers and 1 zombie process.', reasoning: 'Scanned 8 containers. ml-worker-stale: idle 12 days, 0% CPU. test-runner-stale: idle 8 days, 0% CPU. legacy-cron: zombie process, no activity for 90 days.' },
      { id: 'l09', timestamp: '13:40:00', type: 'diagnose', target: 'prod-worker-03', message: 'Memory pressure analysis: Redis cache consuming 42% RAM, axiom-api consuming 35%. Combined load approaching OOMKill threshold.', reasoning: 'Inspected process-level memory usage via /proc/meminfo. Top consumers: redis-cache (42%), axiom-api-prod (35%), nginx-proxy (8%). Swap is disabled. Recommend horizontal pod autoscaling or increasing instance memory.' },
      { id: 'l10', timestamp: '13:32:20', type: 'recommend', target: 'vol-backup-old', message: 'Archive vol-backup-old to S3 Glacier. Last accessed 45 days ago. Save ₹1,080/mo.', reasoning: 'EBS volume vol-backup-old (500GB gp3) has zero read/write IOPS for 45 days. Contents are backup snapshots from February. Migrating to S3 Glacier reduces cost from ₹1,200/mo to ₹120/mo.' },
      { id: 'l11', timestamp: '13:20:05', type: 'flag', target: 'legacy-cron', message: 'Zombie process detected: legacy-cron container. Process running for 90 days with no output.', reasoning: 'Container is in running state but: 0% CPU, 2 MB RAM, zero network I/O. The cron job inside was deprecated 3 months ago. Container should be terminated.' },
      { id: 'l12', timestamp: '13:10:00', type: 'scan', target: 'pipelines', message: 'Pipeline scan complete. 3 failures in last hour: axiom-api (ENOMEM), infra-deploy (TF_LOCK), ml-pipeline (CUDA_OOS).', reasoning: 'Monitored 8 pipeline runs. Failure rate in last hour: 37.5% (3/8). This exceeds the 20% threshold for alert generation. All failures have distinct root causes — no correlated infrastructure issue.' },
    ],
  });
}
